# this code is to find a pattern in given string mean we enter a string and find a number of pattern present
# in this given string and at the end give a number of match pattern

def PattrenCount(Pattren, Text):
    M = len(Pattren)
    N = len(Text)
    res = 0

    # A loop to slide Pattren one by one
    for i in range(N - M + 1):

        # For current index i, check
        # for pattern match
        j = 0
        while j < M:
            if Text[i + j] != Pattren[j]:
                break
            j += 1

        if j == M:
            res += 1
            j = 0
    return res


Text = "TAGCCACCGCCCTTACATAAGGCCATAAGGCATAAGGCATAAGGGCGTGGTCCATAAGGAACCATAAGGCGTCCCATAAGGTCATAAGGCATAAGGCATAAGGGACATAAGGACGGGGCATAAGGCATAAGGCCATAAGGCATAAGGCATAAGGCCATAAGGTCACACCATAAGGCAACCGACATAAGGATCGCATAAGGTATTAGCATAAGGCATAAGGGGCATAAGGCACGTTGAAACTTCATAAGGCCATAAGGCAAGCCATAAGGCCCATAAGGCATAAGGGGCATAAGGCATAAGGGATTCTGCATAAGGATCATAAGGCCCTCATAAGGATCCCACATAAGGCATAAGGCCGTGCATAAGGACATAAGGCCATAAGGCCCAACACATAAGGACATAAGGCATAAGGCGCGACATAAGGCATAAGGGACATAAGGGCATAAGGGTCATAAGGCATAAGGCTCTCCGCATAAGGACCCATAAGGCCATAAGGGTCCCATAAGGTGCATAAGGCCATAAGGTATTGCATAAGGAGCTGACATAAGGCTAGCATAAGGCATAAGGGCCATAAGGGCCATAAGGATGACATAAGGCCGGTGAGCCATAAGGCATAAGGCATAAGGGAGTACATAAGGTCATAAGGCATAAGGCCATAAGGACTATGGACATAAGGGAGGAGCATAAGGCGAATCGCATAAGGGTCATAAGGGCTAGCCATAAGGCAACATAAGGGCATAAGGACCATAAGGCCGCATAAGGATCATAAGGTCATAAGGGTCCATAAGGAACATAAGGGTCATAAGGCCATCCATAAGGCATAAGGAGCATAAGGGTAACATAAGGCCCATAAGGTCATAAGGACCATAAGGCATAAGGCATAAGGAGCATAAGGCATAAGGTACATAAGGCATAAGGCATAAGGCATAAGGGCATAAGGCCCATAAGGATGATTCATAAGGGCATAAGGACATAAGGTGCGCACATAAGG"
Pattren = "CATAAGGCA"
# function calling
print(PattrenCount(Pattren, Text))
